modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="npcmod"
version="1.0.0"
displayName="NPC Mod"
description="A mod that adds NPCs that look like real players using player models."
authors="Master"
displayURL=""
credits=""
logoFile=""
